### ISSUE TITLE
Invoke local seem to be broken

### ISSUE THREAD

**Issue by enykeev** [StackStorm/serverless-plugin-stackstorm#1]
https://github.com/pypa/pip/issues/373 gives me reason to believe this is an upstream issue that would be resolved in the next version of pip.

```
Serverless: Installing StackStorm adapter dependencies

  Error --------------------------------------------------

  Exited with code 2.
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 922, in install
    with open(inst_files_path, 'w') as f:
IOError: [Errno 2] No such file or directory: '~st2/deps/lib/python2.7/site-packages/st2common-2.6.dev0-py2.7.egg-info/installed-files.txt'


     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Exited with code 2.
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 922, in install
    with open(inst_files_path, 'w') as f:
IOError: [Errno 2] No such file or directory: '~st2/deps/lib/python2.7/site-packages/st2common-2.6.dev0-py2.7.egg-info/installed-files.txt'

    at ChildProcess.child.on.code (/Volumes/StackStorm/serverless-plugin-stackstorm/node_modules/nopy/src/api.js:228:20)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:39:50)
    at <anonymous>
```

**Comment by enykeev** [comment]
We've implemented a proper analogue for local invoke in #5: `sls stackstorm docker run`. As for `invoke local`, the problem should be handles on a framework level.
