### ISSUE TITLE
`output` section must be optional

### ISSUE THREAD

**Issue by dzimine** [StackStorm/serverless-plugin-stackstorm#15]
Now if I only set `input`, I got an error: 
```
expected string or buffer: TypeError
Traceback (most recent call last):
  File "/var/task/~st2/handler.py", line 198, in basic
    res = base(*args, **kwargs)
  File "/var/task/~st2/handler.py", line 174, in base
    params=json.loads(output_values),
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

**Comment by enykeev** [comment]
Fixed in #18
