### ISSUE TITLE
Can't find ID on execution_db

### ISSUE THREAD

**Issue by tsblack** [StackStorm/serverless-plugin-stackstorm#32]
Hi There

I'm trying to test a basic stackstorm serverless configuration, but I keep on running into the following issue:

```
Traceback (most recent call last):
  File "/var/task/~st2/deps/lib/python2.7/site-packages/eventlet/hubs/poll.py", line 114, in wait
    listener.cb(fileno)
  File "/var/task/~st2/deps/lib/python2.7/site-packages/eventlet/greenthread.py", line 218, in main
    result = function(*args, **kwargs)
  File "/var/task/~st2/deps/lib/python2.7/site-packages/st2common/runners/utils.py", line 176, in read_and_store_stream
    store_data_func(execution_db=execution_db, action_db=action_db, data=line)
  File "/var/task/~st2/deps/lib/python2.7/site-packages/st2common/services/action.py", line 387, in store_execution_output_data
    execution_id = str(execution_db.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

This appears to be a bug, can you advise?

**Comment by Kami** [comment]
Thanks for reporting this.

We will have a look as soon as we get a chance - it's likely related to some recent code change in StackStorm/st2 repo.

**Comment by tsblack** [comment]
Hiya

I think this may be as a result of the "actionrunner.stream_output" which defaulted to True as of Stackstorm 2.6.0 (Jan 2018). It wasn't clear to me reading through the docs where you set global StackStorm options - can you advise?

**Comment by Kami** [comment]
I believe you are correct.

You need to set it in st2.conf. This means this file in this repo - https://github.com/StackStorm/serverless-plugin-stackstorm/blob/master/stackstorm/st2.conf.

**Comment by Kami** [comment]
I merged #33 into master.

Can you please try to install latest plugin version using npm from git master and let me know if it works?

Once it's confirmed it fixes the issue, I will publish a new version to npm.

**Comment by Kami** [comment]
Thanks for reporting this and confirming the fix.

I pushed a new version with this change to np,.
